# Lab Quiz 1 - Numpy Basics

In [1]:
import numpy as np

In [3]:
### Question 1: Given two arrays; multiply_with_left and multiply_with_right, write a function that generates a multiplication table for each of the elements of the multiply_with_left by multiply_with_right.
# For example, if multiply_with_left = [1, 2, 3] and multiply_with_right = [1, 2, 3, 4], the output should be:
# [[ 1  2  3  4]
#  [ 2  4  6  8]
#  [ 3  6  9 12]]
# The function should return the multiplication table as a numpy array.


def multiplication_table(multiply_with_left, multiply_with_right):
    return np.multiply(multiply_with_left.reshape(-1, 1), multiply_with_right)

In [5]:
### Question 2: Grocery Shopping List Price - Given a list of quantities of items of a grocery list and their prices as numpy arrays, write a function that returns the total price of the grocery list rounded to 2 decimal figures

def grocery_shopping_list_price(item_quantity, item_price):
    return np.round(np.dot(item_quantity, item_price), 2)