In [1]:
import numpy as np

In [2]:
#input embedding
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

In [3]:
# defining weights
W_Q = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9],
    [1.0, 1.1, 1.2]
])

W_K = np.array([
    [0.3, 0.2, 0.1],
    [0.6, 0.5, 0.4],
    [0.9, 0.8, 0.7],
    [1.2, 1.1, 1.0]
])

W_V = np.array([
    [0.7, 0.8, 0.9],
    [0.4, 0.5, 0.6],
    [0.1, 0.2, 0.3],
    [1.3, 1.4, 4.5]
])

In [4]:
# Step 1: Compute Q, K, V
Q = np.dot(X, W_Q)
K = np.dot(X, W_K)
V = np.dot(X, W_V)

print("Q:")
print(Q)
print("\nK:")
print(K)
print("\nV:")
print(V)

Q:
[[ 7.   8.   9. ]
 [15.8 18.4 21. ]]

K:
[[ 9.   8.   7. ]
 [21.  18.4 15.8]]

V:
[[ 7.   8.  21. ]
 [17.  19.6 46.2]]


In [5]:
# Step 2: Compute QK^T
QK_T = np.dot(Q, K.T)

print("\nQK^T:")
print(QK_T)


QK^T:
[[ 190.    436.4 ]
 [ 436.4  1002.16]]


In [6]:
# Step 3: Compute the scaling factor
d_k = K.shape[1]
scaling_factor = np.sqrt(d_k)

print(f"\nd_k: {d_k}")
print(f"Scaling Factor: {scaling_factor}")


d_k: 3
Scaling Factor: 1.7320508075688772


In [7]:
# Step 4: Compute the scaled QK^T
scaled_QK_T = QK_T / scaling_factor

print("\nScaled QK^T:")
print(scaled_QK_T)


Scaled QK^T:
[[109.69655115 251.95565747]
 [251.95565747 578.59734577]]


In [8]:
# Step 5: Apply softmax to the scaled QK^T
def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / e_x.sum(axis=-1, keepdims=True)


softmax_scaled_QK_T = softmax(scaled_QK_T)

print("\nSoftmax Scaled QK^T:")
print(softmax_scaled_QK_T)


Softmax Scaled QK^T:
[[1.65065047e-062 1.00000000e+000]
 [1.38457732e-142 1.00000000e+000]]


In [9]:
A = np.dot(softmax_scaled_QK_T, V)

print("\nSelf-Attention (A):")
print(A)


Self-Attention (A):
[[17.  19.6 46.2]
 [17.  19.6 46.2]]
